---
title: "Thank you blogdown, hello distill"
description: |
  A short description of the post.

date: 02-12-2021

draft: T

author:
  - first_name: "Roland"
    last_name: "Schmidt"
    url: https://werk.statt.codes
    orcid_id: 0000-0002-6897-1693
categories:
  - distill
  
#preview: 2020-10-10-vienna-elections-2020-age-profile/preview.png
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: false
    code_folding: TRUE
creative_commons: CC BY-NC-SA
editor_options: 
  chunk_output_type: console

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

So, I moved my collection of posts from blogdown to distill. What pulled me to the latter was the perspective of a simpler, yet effective means to put posts on the web. Blogdown undoubtedly can be a very powerful tool and the web is full of visually very appealing blog (just see here) and the speed of its underlying Hugo language seems unrivaled.

Yet, after using it for about a year or so, I found the lack of/the required work to get some features running too cumbersome. Hence, the move to distill.

Among the helpful resources which made the transition rather smooth, I'd like to particularly highlight the documents on RStudio's distill [site](https://rstudio.github.io/distill/){target="_blank"}, [Thomas Mock's](https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/){target="_blank"} and [Lisa Lendway's](https://lisalendway.netlify.app/posts/2020-12-09-buildingdistill/){target="_blank"} related posts. I also found it helpful to have a look at the code underlying the blogs of [Miles McBain](https://milesmcbain.xyz/){target="_blank"} or others who have made their repositories publicly available on github. And last, but certainly not least, the authors and maintainers of the package who were overwhelmingly quite quick to respond to issues I had posted on [github](https://github.com/rstudio/distill){target="_blank"}. So essentially, I don't have much too add, except a few details which I thought might be helpful to those blogdown users considering the switch. 

## Search function
Distill comes with a search function which can be activated by setting the pertaining option to true in the site's yml file. Two points here:
1) The search field will become visible only *after having the site deployed*. I was wondering for a while what was wrong with with my setup since the search field didn't show up. An alternative to deploying is to test run the site with the search fied is to 'virtually' run the site with the servr package (ht to )





Search function:
  Not that the search bar will only show up once you've deployed your site (e.g. via githut to netlify). 
  I initially was trying to find an error until I mustered the courage to post a pertaining question on github, and
  Jeff was kind enough to quickly respond. The mentioned 'sevr' package gives you a handy tool to test-drive your
  site before deploying.
  
Where to put static files:
_blog_data

theming:
css 

performance:
tick slower than blogdown / based on hugo

  
  
  

