---
title: "ggiraph text test"
description: |
  A short description of the post.
author:
  - name: Roland Schmidt
    url: https://werk.statt.codes
date: 02-17-2021
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```



```{r}
library(ggplot2)
library(ggiraph)
library(svglite)
library(ggtext)
library(hrbrthemes)
library(extrafont)
data <- mtcars
data$carname <- row.names(data)

```



```{r eval=T}
theme_post <- function() {
  hrbrthemes::theme_ipsum_rc() +
    theme(
      # plot.background = element_rect(fill = plot_bg_color, color=NA),
      # panel.background = element_rect(fill = plot_bg_color, color=NA),
      # panel.border = element_rect(colour = plot_bg_color, fill=NA),
      # plot.border = element_rect(colour = plot_bg_color, fill=NA),
      plot.margin = margin(l = 0, 
                           t = 0.25,
                           unit = "cm"),
      plot.title = element_markdown(
        color = "grey20",
        face = "bold",
        margin = margin(l = 0, unit = "cm"),
        size = 13
      ),
      plot.title.position = "plot",
      plot.subtitle = element_text(
        color = "grey50",
        margin = margin(t = 0.2, b = 0.3, unit = "cm"),
        size = 11
      ),
      plot.caption = element_text(
        color = "grey50",
        size = 8,
        hjust = c(0)
      ),
      plot.caption.position = "panel",
      axis.title.x = element_text(
        angle = 0,
        color = "grey50",
        hjust = 1
      ),
      axis.text.x = element_text(
        size = 9,
        color = "grey50"
      ),
      axis.title.y = element_blank(),
      axis.text.y = element_text(
        size = 9,
        color = "grey50"
      ),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.spacing = unit(0.25, "cm"),
      panel.spacing.y = unit(0.25, "cm"),
      strip.text = element_text(
        angle = 0,
        size = 9,
        vjust = 1,
        face = "bold"
      ),
      legend.title = element_text(
        color = "grey30",
        face = "bold",
        vjust = 1,
        size = 9
      ),
      legend.text = element_text(
        size = 9,
        color = "grey30"
      ),
      legend.justification = "left",
      legend.box = "horizontal", # arrangement of multiple legends
      legend.direction = "vertical",
      legend.margin = margin(l = 0, t = 0, unit = "cm"),
      legend.spacing.y = unit(0.07, units = "cm"),
      legend.text.align = 0,
      legend.box.just = "top",
      legend.key.height = unit(0.2, "line"),
      legend.key.width = unit(0.5, "line"),
      text = element_text(size = 5)
    )
}
```


# Normal, theme_minmal

```{r}
gg_point = ggplot(data = data) +
  labs(title="long title long title long title")+
    geom_point_interactive(aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  theme_minimal()

girafe(ggobj = gg_point)
```



# Normal, theme_minmal, plot_title_elmenent_markdown

```{r}
gg_point = ggplot(data = data) +
  labs(title="long title long title long title")+
    geom_point_interactive(aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  theme_minimal()+
  theme(plot.title=element_markdown())

girafe(ggobj = gg_point)
```

# Normal, theme_minmal, plot_title_elmenent_markdown, device svglite

```{r, dev="svglite"}
gg_point = ggplot(data = data) +
  labs(title="long title long title long title")+
    geom_point_interactive(aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  theme_minimal()+
  theme(plot.title=element_markdown())

girafe(ggobj = gg_point)
```

# Normal, theme_post, plot_title_elmenent_markdown, device svglite

```{r, dev="svglite"}
gg_point = ggplot(data = data) +
  labs(title="long title long title long title")+
    geom_point_interactive(aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  theme_post()+
  theme(plot.title=element_markdown())

girafe(ggobj = gg_point)
```

# Normal, theme_ipsum_rc, plot_title_elmenent_markdown, device svglite

```{r dev="svglite", eval=T}
gg_point = ggplot(data = data) +
  labs(title="long title long title long title")+
    geom_point_interactive(aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  theme_ipsum_rc()+
  theme(plot.title=element_markdown())

girafe(ggobj = gg_point)
```



