---
title: "reactablefmtr and title size issue?"
description: |
  A short description of the post.
author:  
  - first_name: "Roland"
    last_name: "Schmidt"
    url: https://werk.statt.codes
    orcid_id: 0000-0002-6897-1693
date: 08-19-2021
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: false
    code_folding: TRUE
---

This is quick test of how to change the font size in tables created by `reactable` and formated with the `reactablefrmtr` package.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
library(reactable)
library(reactablefmtr)
```



# table without font size defined

```{r}
mtcars %>% 
  reactable() %>% 
  add_title(title="this is a title without font-size defined")
```

# table with font size 20

```{r}
mtcars %>% 
  reactable() %>% 
  add_title(title="this is a title in font 20",
            font_size = 20)
```

# table with font size 5

```{r}
mtcars %>% 
  reactable() %>% 
  add_title(title="this is a title in font 20",
            font_size = 5)
```


